# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id_dificultad', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dificultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.CharField(max_length=1000)),
                ('clave1', models.CharField(max_length=200)),
                ('clave2', models.CharField(max_length=200)),
                ('clave3', models.CharField(max_length=200)),
                ('clave4', models.CharField(max_length=200)),
                ('clave5', models.CharField(max_length=200)),
                ('correcta', models.CharField(max_length=200)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('correcta_num', models.SmallIntegerField(blank=True, null=True)),
                ('informacion', models.CharField(blank=True, max_length=800, null=True)),
            ],
            options={
                'db_table': 'pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('acertada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id_subtema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subtema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id_tipopregunta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipo_pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('nombres', models.CharField(blank=True, max_length=80, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=80, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioHasAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_has_asignatura',
                'managed': False,
            },
        ),
    ]
