# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dificultad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subtema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipopregunta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuariohasasignatura',
            options={},
        ),
    ]
