# Generated by Django 2.0.6 on 2018-06-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20180507_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'usuario_asignatura',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSubtema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'usuario_subtema',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'usuario_tema',
            },
        ),
        migrations.DeleteModel(
            name='UsuarioHasAsignatura',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='correcta',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_dificultad',
            field=models.ForeignKey(db_column='id_dificultad', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Dificultad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_subtema',
            field=models.ForeignKey(db_column='id_subtema', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Subtema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_tipopregunta',
            field=models.ForeignKey(db_column='id_tipopregunta', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.TipoPregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id_pregunta',
            field=models.ForeignKey(db_column='id_pregunta', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Pregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtema',
            name='id_tema',
            field=models.ForeignKey(db_column='id_tema', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Tema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='id_asignatura',
            field=models.ForeignKey(db_column='id_asignatura', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Asignatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='monedas',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='id_subtema',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='id_respuesta',
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('id_usuario', 'id_pregunta')},
        ),
        migrations.AddField(
            model_name='usuariotema',
            name='id_tema',
            field=models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Tema'),
        ),
        migrations.AddField(
            model_name='usuariotema',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Usuario'),
        ),
        migrations.AddField(
            model_name='usuariosubtema',
            name='id_subtema',
            field=models.ForeignKey(db_column='id_subtema', on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Subtema'),
        ),
        migrations.AddField(
            model_name='usuariosubtema',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Usuario'),
        ),
        migrations.AddField(
            model_name='usuarioasignatura',
            name='id_asignatura',
            field=models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Asignatura'),
        ),
        migrations.AddField(
            model_name='usuarioasignatura',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariotema',
            unique_together={('id_usuario', 'id_tema')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariosubtema',
            unique_together={('id_usuario', 'id_subtema')},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioasignatura',
            unique_together={('id_usuario', 'id_asignatura')},
        ),
    ]
