# Generated by Django 2.0.6 on 2018-06-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'usuario_asignatura',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSubtema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'usuario_subtema',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'usuario_tema',
            },
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dificultad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subtema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipopregunta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='usuariotema',
            name='id_tema',
            field=models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Tema'),
        ),
        migrations.AddField(
            model_name='usuariotema',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Usuario'),
        ),
        migrations.AddField(
            model_name='usuariosubtema',
            name='id_subtema',
            field=models.ForeignKey(db_column='id_subtema', on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Subtema'),
        ),
        migrations.AddField(
            model_name='usuariosubtema',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Usuario'),
        ),
        migrations.AddField(
            model_name='usuarioasignatura',
            name='id_asignatura',
            field=models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Asignatura'),
        ),
        migrations.AddField(
            model_name='usuarioasignatura',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariotema',
            unique_together={('id_usuario', 'id_tema')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariosubtema',
            unique_together={('id_usuario', 'id_subtema')},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioasignatura',
            unique_together={('id_usuario', 'id_asignatura')},
        ),
    ]
