# Generated by Django 2.0.6 on 2018-06-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0002_auto_20180603_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='correcta',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='correcta_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_dificultad',
            field=models.ForeignKey(db_column='id_dificultad', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Dificultad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_subtema',
            field=models.ForeignKey(db_column='id_subtema', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Subtema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_tipopregunta',
            field=models.ForeignKey(db_column='id_tipopregunta', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.TipoPregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='informacion',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id_pregunta',
            field=models.ForeignKey(db_column='id_pregunta', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Pregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtema',
            name='id_tema',
            field=models.ForeignKey(db_column='id_tema', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Tema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='id_asignatura',
            field=models.ForeignKey(db_column='id_asignatura', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='webadmin.Asignatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='monedas',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='id_subtema',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('id_usuario', 'id_pregunta')},
        ),
        migrations.AlterModelTable(
            name='asignatura',
            table='asignatura',
        ),
        migrations.AlterModelTable(
            name='dificultad',
            table='dificultad',
        ),
        migrations.AlterModelTable(
            name='pregunta',
            table='pregunta',
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table='respuesta',
        ),
        migrations.AlterModelTable(
            name='subtema',
            table='subtema',
        ),
        migrations.AlterModelTable(
            name='tema',
            table='tema',
        ),
        migrations.AlterModelTable(
            name='tipopregunta',
            table='tipo_pregunta',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='id_respuesta',
        ),
    ]
